### ISSUE TITLE
New XMOG sharing is broken by WIM.

### ISSUE THREAD

**Issue by zaphon** [Legacy-of-Sylvanaar/wow-instant-messenger#1]
**Describe the bug**
If a user whispers you a XMOG link (via the dressing room option to share a XMOG) it is broken (the same thing happens if someone links you a WeakAura, an invitation to join a Community, coordinate links, etc., WIM just breaks it)

**To Reproduce**
Have someone whisper you a XMOG link

**Expected behavior**
The link to work just like it does when WIM isn't installed.

**Additional context**
As I mentioned I actually opened a bug against the original WIM a few years back when communities were added as friends kept whispering me invitations and I could never get them to work without disabling WIM. Same with WeakAuras. I found if I just invite my friend to a party and have them send it to me via Party Chat (doesn't go through WIM for me), I could get around it. But now with XMOG's being sharable, it feels like it's a good time to actually fix this.

**Comment by Pazza** [comment]
I just pushed an update to the stable channel. It should fix all hyperlinks within WIM windows. Let me know if everything is working.

**Comment by zaphon** [comment]
Had a chance to test this, and here's my results

1. Outfit Link - Works perfect
2. Coordinates Link - Works perfect
3. Community Invite - Generates the following when you click the link shared (so it's getting through, but just like typing /logout or /quit in a WIM chat window, it doesn't like being clicked from there)

> 1x [ADDON_ACTION_FORBIDDEN] AddOn 'WIM' tried to call the protected function 'GetLastTicketResponse()'.
> [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
> [string "=[C]"]: in function `GetLastTicketResponse'
> [string "@Blizzard_Communities\CommunitiesHyperlink.lua"]:10: in function <Blizzard_Communities\CommunitiesHyperlink.lua:7>
> 

4. WeakAura share - This is the odd one, no message is received, it just gets eaten up. I was sent multiple weakaura links and while they could see them being sent on their side (no WIM loaded), on my side, I got nothing. This is different than before, I'd get a link before it just wouldn't work.

**Comment by Pazza** [comment]
@zaphon I updated retail (since i never log into it) to test these things out. In regard to WeakAura, it is working for me without a problem. I am not familiar with communities to test the invite links, but that too should work. I believe that there may be a conflict with another addon. Would you please test these actions with only WIM and WeakAura loaded (and BugGrabber) and see if the problem still exists? Again, the only thing that WIM is doing is calling the default chat frame's OnHyperLinkShow function.

Thanks.

**Comment by zaphon** [comment]
Did some more testing, you're right the WeakAura links come through. My issue was I had done my testing in the order that I responded in. So I had sent a community invite (what I did was had my friend create a community (for testing) and send me an invite), when I clicked it from the WIM window I got the error above (which as I noted I have seen similar behavior before if you try and do protected things from the WIM window such as simply typing /quit inside of a WIM chat window). After the error above, WeakAura links no longer come through. If I do my testing of WeakAura by themselves on a clean UI, works fine.

So I appreciate the response, and honestly not sure if you can get around the Protected Function stuff that the community link is triggering, so it may be a lost cause anyway. I've redone this test with just WIM loaded and same error, so it's not another addon in this scenario.

**Comment by Pazza** [comment]
Thank you for putting in the time to test this. Unfortunately I do not think there is something I can do about this. The securecall function provided by WoW, helps to preserve your own secure state when calling another function that might have been tainted by another source. Not to allow you to call a protected function itself.

There might be one thing I can try, and that would be to attach the handler directly to the ScrollingChatFrame opposed to calling it within my own function. Not sure if that makes a difference or not, likely it will not work.

I'll let you know, maybe i'll post an alpha for you to test.

**Comment by Pazza** [comment]
Actually, scratch that, I was just reviewing how i wrote the registration for widget events, unfortunately what i suggested isn't possible. We are going to have to chalk this one up to something we can't navigate around. Perhaps if someone else has a suggestion.

Thanks again for your help. Glad the other items were fixed.
