### ISSUE TITLE
WIM latest version won't load on SoD

### ISSUE THREAD

**Issue by thila182** [Legacy-of-Sylvanaar/wow-instant-messenger#105]
**Describe the bug**
Addon is no loading in SoD Classic, Tried latest version, also version WIM-3.12.5 and also don't load but version 3.12.4 works fine

**To Reproduce**
1. Install addon on SoD
2. Go to addons
3. WIM not there

**Expected behavior**
Should load on SoD

**Comment by BreakBB** [comment]
Also doesn't load on Anniversary servers. Last working version is 3.12.4

**Comment by Pazza** [comment]
I'll revert the TOC versioning format. That might be the issue.

**Comment by plusmouse** [comment]
The solution to this bug is to restart your WoW client to get WoW to accept the changed format.
