### ISSUE TITLE
Request: Make it easier to handle window hide/restore

### ISSUE THREAD

**Issue by JRDK92** [Legacy-of-Sylvanaar/wow-instant-messenger#106]
I'd like to see an easier and more intuitive and clear way to manage window behavior. When I installed WIM, I was surprised to find the window disappear when I went into a dungeon, and it refused to display again! Very annoying. Ok, how do I stop that? 'Window Settings'? Nope. Display settings? Also no. 'Expose' has this feature. It could honestly just go under window or display, with a scroll bar to scroll down. This is a bit confusing and non-intuitive, probably because I'm not a Mac user. 

![image](https://github.com/user-attachments/assets/0033e0e4-ee8e-40db-9ed9-56a76df147ea)

**Comment by Pazza** [comment]
Fortunately, setting it up is usually a one and done activity. The addon is in maintenance mode. I don't plan on rewriting its settings window.
