### ISSUE TITLE
errors when switching between tabbed conversations

### ISSUE THREAD

**Issue by filleadh** [Legacy-of-Sylvanaar/wow-instant-messenger#11]
**Describe the bug**
This behaviour happens occasionally, that after several messages and switching between conversations, I get the following errors:

Message: Interface\AddOns\WIM\Sources\TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
Time: Thu Sep  8 16:02:44 2022
Count: 4
Stack: Interface\AddOns\WIM\Sources\TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\WIM\Sources\TabHandler.lua"]:486: in function `JumpToTab'
[string "@Interface\AddOns\WIM\Sources\TabHandler.lua"]:332: in function <Interface\AddOns\WIM\Sources\TabHandler.lua:327>

Locals: 

Message: Interface\AddOns\WIM\Sources\TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
Time: Thu Sep  8 16:01:20 2022
Count: 1
Stack: Interface\AddOns\WIM\Sources\TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\WIM\Sources\TabHandler.lua"]:486: in function `JumpToTab'
[string "@Interface\AddOns\WIM\Sources\TabHandler.lua"]:537: in function `Detach'
[string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:1455: in function <Interface\AddOns\WIM\Sources\WindowHandler.lua:1445>
[string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:1789: in function `fun'
[string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:393: in function <Interface\AddOns\WIM\Sources\WindowHandler.lua:385>
[string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:709: in function <Interface\AddOns\WIM\Sources\WindowHandler.lua:709>

Locals: 

Message: Interface\AddOns\WIM\Sources\TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
Time: Thu Sep  8 16:01:31 2022
Count: 1
Stack: Interface\AddOns\WIM\Sources\TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\WIM\Sources\TabHandler.lua"]:486: in function `JumpToTab'
[string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:1123: in function `Pop'
[string "@Interface\AddOns\WIM\Modules\Menu.lua"]:98: in function <Interface\AddOns\WIM\Modules\Menu.lua:93>

Locals:

**Comment by filleadh** [comment]
I'll keep trying to see if I can pinpoint the issue, but I notice it usually happens when I have multiple conversations going on at a time. and only then.   It doesn't seem to happen if i "HAD" multiple conversations/tabs and just currently talking to one, but does when I have more than just one whisper convo going.

**Comment by Pazza** [comment]
I almost think it is a blizzard issue because it's the same code from like a decade ago. And it appears to happen when repositioning too quickly.

**Comment by Pazza** [comment]
Its probably a long shot, but while making some fixes for Dragonflight, I found a bug where i was setting parent to a string of UIParent instead of actual UI parent... The alpha posted on curse has the fix in it. Give it a shot, I'd be curious if this fixes our issue. 🤞

**Comment by filleadh** [comment]
To be honest, I forgot about this, and haven't seen the issue pop up after wotlk launch, so perhaps it was a blizzard issue, but I'll keep an eye open (incidentally, I also don't have as many conversations going at the same time as I used to either).

**Comment by wrekh** [comment]
I've raised a another bug about it before I noticed this issue. It usually happens when I get a lot of whispers about Crafting Orders.

I guess it's the same thing, hopefully Blizzard will fix it.

> 18x WIM/Sources/TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame3:SetPoint.
> [string "=[C]"]: in function `SetPoint'
> [string "@WIM/Sources/TabHandler.lua"]:486: in function `JumpToTab'
> [string "@WIM/Sources/TabHandler.lua"]:332: in function <WIM/Sources/TabHandler.lua:327>
> 
> Locals:
> (*temporary) = WIM3_msgFrame3 {
>  0 = <userdata>
>  fadeOut = <function> defined @WIM/Sources/WindowHandler.lua:860
>  class = "Shaman"
>  isNew = false
>  offScreen = 0
>  msgSent = false
>  level = ""
>  Hide_Normal = <function> defined =[C]:-1
>  Hide = <function> defined @WIM/Sources/WindowHandler.lua:1255
>  isOnHyperLink = false
>  fadedIn = true
>  msgWaiting = false
>  animation = <table> {
>  }
>  Pop = <function> defined @WIM/Sources/WindowHandler.lua:1138
>  isWimWindow = true
>  age = 450539.590000
>  delayFade = false
>  delayFadeElapsed = 0
>  classColor = "2459FF"
>  SendWho = <function> defined @WIM/Sources/WindowHandler.lua:1023
>  AddMessageRaw = <function> defined @WIM/Sources/WindowHandler.lua:931
>  SafeGetTop = <function> defined @WIM/Sources/WindowHandler.lua:1303
>  animators = <table> {
>  }
>  AddMessage = <function> defined @WIM/Sources/WindowHandler.lua:924
>  helperFrame = WIM_WindowHelperFrame {
>  }
>  SafeGetRight = <function> defined @WIM/Sources/WindowHandler.lua:1300
>  UpdateIcon = <function> defined @WIM/Sources/WindowHandler.lua:946
>  guild = ""
>  WhoCallback = <function> defined @WIM/Sources/WindowHandler.lua:1011
>  customSize = true
>  lastDate = "12/22/2022"
>  SetScale_Orig = <function> defined =[C]:-1
>  GetRuleSet = <function> defined @WIM/Sources/WindowHandler.lua:1128
>  isMoving = false
>  race = "Goblin"
>  lastActivity = 450585.608000
>  theUser = "Bezzl"
>  fadeElapsed = 0
>  AddEventMessage = <function> defined @WIM/Sources/WindowHandler.lua:935
>  unreadCount = 0
>  bn = <table> {
>  }
>  initialized = true
>  type = "whisper"
>  UpdateCharDetails = <function> defined @WIM/Sources/WindowHandler.lua:1007
>  tabStrip = WIM_TabStrip1 {
>  }
>  hasMoved = true
>  SafeGetLeft = <function> defined @WIM/Sources/WindowHandler.lua:1297
>  isHistory = true
>  widgets = <table> {
>  }
>  SafeGetBottom = <function> defined @WIM/Sources/WindowHandler.lua:1306
>  online = true
>  UpdateProps = <function> defined @WIM/Sources/WindowHandler.lua:1203
>  SetScale = <function> defined @WIM/Sources/WindowHandler.lua:818
>  location = ""
>  isParent = true
>  fadeIn = <function> defined @WIM/Sources/WindowHandler.lua:859
>  ResetAnimation = <function> defined @WIM/Sources/WindowHandler.lua:1283
> }
> (*temporary) = "TOPLEFT"
> (*temporary) = WIM_UIParent {
>  0 = <userdata>
>  _editBoxInFocusElapsed = 0.071000
> }
> (*temporary) = "BOTTOMLEFT"
> (*temporary) = 52.395500
> (*temporary) = 592.499451
>

**Comment by Pazza** [comment]
Reopened this since the problem still exists apparently. This seems like its going to be a difficult one to track down.

**Comment by Jorvanus** [comment]
I opened a separate one, but I also have this issue. Definitely had multiple tabs open, with different people messaging me.  I was unable to switch back to the tab in question giving this error. 

https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/issues/32

**Comment by Kirri777** [comment]
Error from BugSack
Before error i moved window a little.

```
2x WIM/Sources/TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@WIM/Sources/TabHandler.lua"]:486: in function `JumpToTab'
[string "@WIM/Sources/TabHandler.lua"]:332: in function <WIM/Sources/TabHandler.lua:327>

Locals:
(*temporary) = WIM3_msgFrame4 {
 0 = <userdata>
 fadeOut = <function> defined @WIM/Sources/WindowHandler.lua:860
 class = "Monk"
 isNew = false
 AddMessageRaw = <function> defined @WIM/Sources/WindowHandler.lua:931
 offScreen = 0
 msgSent = false
 level = ""
 unreadCount = 1
 Hide = <function> defined @WIM/Sources/WindowHandler.lua:1255
 fadedIn = true
 lastDate = "02/02/2023"
 animation = <table> {
 }
 Pop = <function> defined @WIM/Sources/WindowHandler.lua:1138
 isWimWindow = true
 age = 275166.833000
 isParent = true
 isHistory = true
 tabStrip = WIM_TabStrip1 {
 }
 Hide_Normal = <function> defined =[C]:-1
 SafeGetTop = <function> defined @WIM/Sources/WindowHandler.lua:1303
 msgWaiting = true
 AddMessage = <function> defined @WIM/Sources/WindowHandler.lua:924
 helperFrame = WIM_WindowHelperFrame {
 }
 SafeGetRight = <function> defined @WIM/Sources/WindowHandler.lua:1300
 UpdateIcon = <function> defined @WIM/Sources/WindowHandler.lua:946
 guild = ""
 isOnHyperLink = false
 customSize = true
 SendWho = <function> defined @WIM/Sources/WindowHandler.lua:1023
 SetScale_Orig = <function> defined =[C]:-1
 GetRuleSet = <function> defined @WIM/Sources/WindowHandler.lua:1128
 isMoving = false
 race = "Orc"
 lastActivity = 275296.703000
 theUser = "Cravla"
 animators = <table> {
 }
 AddEventMessage = <function> defined @WIM/Sources/WindowHandler.lua:935
 WhoCallback = <function> defined @WIM/Sources/WindowHandler.lua:1011
 initialized = true
 type = "whisper"
 bn = <table> {
 }
 UpdateCharDetails = <function> defined @WIM/Sources/WindowHandler.lua:1007
 hasMoved = true
 SafeGetLeft = <function> defined @WIM/Sources/WindowHandler.lua:1297
 UpdateProps = <function> defined @WIM/Sources/WindowHandler.lua:1203
 widgets = <table> {
 }
 SafeGetBottom = <function> defined @WIM/Sources/WindowHandler.lua:1306
 online = true
 classColor = "00ff96"
 SetScale = <function> defined @WIM/Sources/WindowHandler.lua:818
 location = ""
 fadeIn = <function> defined @WIM/Sources/WindowHandler.lua:859
 ResetAnimation = <function> defined @WIM/Sources/WindowHandler.lua:1283
}
(*temporary) = "TOPLEFT"
(*temporary) = WIM_UIParent {
 0 = <userdata>
 _editBoxInFocusElapsed = 0.067000
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = 1521.667236
(*temporary) = 1143.999756
```

**Comment by ChrisKader** [comment]
I was able to replicate and fix this locally. Will submit a PR.

**Comment by Pazza** [comment]
@ChrisKader that is very much appreciated.

**Comment by Pazza** [comment]
@ChrisKader any update on this. I'd be curious to see your fix.

**Comment by MelchiorGaspar** [comment]
I just experienced this issue as well.. lol..

**Comment by Pazza** [comment]
I found and fixed the problem finally.
