### ISSUE TITLE
Typo in Settings

### ISSUE THREAD

**Issue by NathanPrice** [Legacy-of-Sylvanaar/wow-instant-messenger#13]
**Describe the bug**
Hi, saw a typo in the "Filtering" panel in options. Says "handlef" instead of "handled". Just thought I'd mention / point it out so it could be fixed sometime down the line as it's an easy fix.

**To Reproduce**
1. Type /wim
2. Click the "Filtering" option
3. Typo will appear in the message text

**Expected behavior**
Should say "handled" instead of "handlef"

**Screenshots**
https://prnt.sc/lz8k7ztlaq3p

**Comment by Pazza** [comment]
Thank you
