### ISSUE TITLE
NewcomerChat does not open in new window

### ISSUE THREAD

**Issue by skippy439** [Legacy-of-Sylvanaar/wow-instant-messenger#15]
**Describe the bug**
While configuring WIM v3.9.9 I am attempting to configure Newcomer Chat to open in a WIM window so it is easier for me to keep an eye on.  I have configured World Chat to be enabled, and selected NewcomerChat.  I can see the chat messages in the channel, but do not get a popup from WIM

**To Reproduce**
1. Go to Chat
2. Click on World Chat
3. Check the Enable box
4. Scroll down to NewcomerChat
5. Enable the checkbox next to NewcomerChat

**Expected behavior**
Messages into the Newcomer Chat should popup in a WIM window at the default location

**Screenshots**
https://imgur.com/Hkpx0P0

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by skippy439** [comment]
I have the Pop-Up window when message is received, but not when sent

https://imgur.com/temnwYS

I don't suppose there is a way to turn on a tracing of sorts?

**Comment by Pazza** [comment]
Hmm... I'll have to try it on retail. I only tested it on wrath and general was working correctly.

there is `/wim debug`. That will output events etc within WIM's framework. Not sure if you'll see what you're looking for. I'll try to try it on retail or PTR
