### ISSUE TITLE
Possible Error with ElvUI 13.01

### ISSUE THREAD

**Issue by Merathilis** [Legacy-of-Sylvanaar/wow-instant-messenger#21]
**Describe the bug**

**To Reproduce**
1. Download ElvUI 13.01 or later
2. Have WIM + ElvUI enabled at the same time.
3. Whisper someone an emoji

**Expected behavior**
No error and the message should be visible.

**Screenshots**
Sadly the BugSack frame from the error is empty for this, so i can only send you this screenshot:
![image](https://user-images.githubusercontent.com/272403/201487554-96855cbe-b157-4efa-a375-d5b822e699d9.png)

**Additional context**
It might could be that ElvUI implemented to LibDeflate, but i really dont have a clue right now.

**Comment by Gogo1951** [comment]
Also saw this. Also saw it with sending <Guild Names>.

**Comment by gOOvER** [comment]
i can confirm this; since i updated ElvUI to 13.01, i cant send any Emotes via WIM

**Comment by Pazza** [comment]
Looks like its related to ElvUI's change from LibCompress to LibDeflate which is causing problems. I'm not exactly sure why but we're having a problem when both WIM's emoticons and ElvUI's emoticons are enabled at the same time. Disabling one seems to fix the issue.

**Comment by Pazza** [comment]
Did some digging and I believe the problem is that ElvUI is encoding the strings using the `%##` escape syntax. When run through the pattern matcher `gsub`, % is used to indicate a capture paramter. I'm trying to see if there is something I can do on my end to get around this.
