### ISSUE TITLE
Whispers are sometimes neither appearing in chat window, nor in WiM window, effectively making them lost (but the receiver still receives it).

### ISSUE THREAD

**Issue by KevinMallinson** [Legacy-of-Sylvanaar/wow-instant-messenger#22]
**Describe the bug**
When using WiM, normally if you whisper someone, it will appear in the WiM window.
However, in maybe 1/10 whispers since updating, the whisper will fail to appear anywhere - it won't appear in the chat window & it also won't appear in the WiM whisper window.

**To Reproduce**
Unknown - it appears to be random.

**Expected behavior**
The message should appear in either chat window or WiM window.

**Screenshots**
Nil.

**Additional context**
I'm currently using ElvUI which might be affecting this.
WoTLK Classic.

**Comment by dxeba2711** [comment]
It's the ElvUI Bug [https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/issues/21](url)

**Comment by Pazza** [comment]
Duplicate #21
