### ISSUE TITLE
WIM add '0' at the start of the text in Wow generic chat when whispering 

### ISSUE THREAD

**Issue by mfhalckon** [Legacy-of-Sylvanaar/wow-instant-messenger#23]
Hello

When whispering , WIM add a "0" in front of the text in the WOW generic chat , not in the WIM windows

Output WIM: [PlayerName]: Text
Output General WOW Chat: 0À [PlayerName] : Text

À is normal in the french version.

**Comment by Pazza** [comment]
I'm having a hard time reproducing this. Can you confirm it happens when all other addons are disabled?

**Comment by mfhalckon** [comment]
I confirm, but it dissapeared when i installed Prat 3.0

**Comment by Pazza** [comment]
Bizarre... So it is working now?
