### ISSUE TITLE
The hyperlinks for new dragonflight items with quality information are not parsed correctly.

### ISSUE THREAD

**Issue by stroeckx** [Legacy-of-Sylvanaar/wow-instant-messenger#25]
**Describe the bug**
When linking one of the dragonflight items  these hyperlinks are not parsed fully causing the text to show a lot of bonus id's, icon information, etc.

**To Reproduce**
send any item with quality through a whisper. here are the examples I noticed:
- A material that has different qualities
- The preview version of a crafted gear item, the ones where instead of stats it shows random stat 1/2
- A crafted version of that item.

**Comment by Pazza** [comment]
I'm not sure that this is caused by WIM or by another addon. When an item is clicked in WIM, it is opened using Blizzards default handler. Can you try testing this with only WIM loaded and see if it is still an issue?

**Comment by Jaidy88** [comment]
![image](https://user-images.githubusercontent.com/47262722/207854258-d811a19b-717f-4be6-814f-441858e2565c.png)

Tested with only wim active, its the same issue

**Comment by Pazza** [comment]
Thank you, the screenshot is helpful. Looks like they added a new escape code. |A

**Comment by Pazza** [comment]
If you can, install the alpha i posted on curseforge. See if that fixes it please.

**Comment by stroeckx** [comment]
It appears to be fixed with the alpha version, thank you!

**Comment by Pazza** [comment]
Thanks for testing it.
