### ISSUE TITLE
Bnet message character size increase

### ISSUE THREAD

**Issue by Gatheringofravens** [Legacy-of-Sylvanaar/wow-instant-messenger#30]
**Is your feature request related to a problem? Please describe.**
Too many message send request API hits in a short period can get you throttled.

The community API and Battle.net whispers let you send messages that are as long as 4000 characters. WIM currently only supports 255.

**Describe the solution you'd like**
Increase the send message character limit for battlenet messages and battlenet community messages from the current cap of 255 to something larger, 400-800 would be great. May need testing to determine what the maximum range would be for it to still look and work acceptably but 400 should be no issue.

**Describe alternatives you've considered**
N/A 
Disabling WIM isn't ideal as it still has many features I want such as unified character history.

**Additional context**
Statement: The community API and Battle.net whispers let you send messages that are as long as 4000 characters.

This is in contrast to the standard SendChatMessage which has always been limited to 255 characters. As an RPer having the ability to send longer messages would be massively beneficial even if only among bnet friends as at this point WoW's low chat limit size (compared to newer games for example FF14) is problematic for more in depth discussions as well as creative writing. I know WIM is very popular among the RP population for its history features among others.

This would also benefit many other non-RPers and it looks nicer to have less breaks in messages.

My suggestion is to check if the messages being sent are bnet whispers (or community messages but bnet whispers would get more use by far) and if so use separate logic to allow an increased size. This would require changing a number of checks in several modules (most of which are obviously connected and which I found just by searching "255" in the lua).

As to the size, there is the consideration that 4000 characters is likely far too big a value, it would make dealing with messages unmanageable as far as displaying or even scrolling through them and likely require extensive changes to WIM's scroll logic. It would also be overwhelming to the user. Instead I propose a raised but still reasonable character limit of 400-800 characters or else allowing the player to configure the limit themselves with a slider control (more work though...)

Looking at an addon in the same space called "emotesplitter" the author there chose 400 characters and receiving messages from those using that from others displays 400 character messages just fine in a WIM window (even I think in the default size) and presents no scroll issues.

As an example of how this benefits, let's say I send a message of 3100 characters in length. Not uncommon for some RP's I've had. With the present WIM limits that message would be broken up into 13 different small chunk messages. With my proposed 400 character size it would be only 8 messages. This /should/ help prevent throttling by hitting the server with fewer message send API requests at once when sending large messages (in particular I've noticed a tendency for the server at times to discard messages beyond 10).

It also simply looks nicer for longer writing/messages and also may mean many cases where instead of a say 300-400 character message being split into two, just using one message to do the same job.

**Comment by Pazza** [comment]
Thanks for the explanation I will take a look

**Comment by Pazza** [comment]
Try out the alpha and see if that works for you.
