### ISSUE TITLE
Trade channel: Invalid channel name

### ISSUE THREAD

**Issue by Faycop** [Legacy-of-Sylvanaar/wow-instant-messenger#34]
Hi! Thanks for this addon, is really great to organize whispers and trade chat for the selling crafting process in DF :)

I just want to let you know that I have an error on the trade window. I've setted WIM to show trade channel on a different WIM window but when I leave the city it gives me an error on the WIM window "Invalid channel name" and re-entering the city won't join Trade channel back again.

I have to logout and login and type "/join Trade" to be able to see trade channel again.

I've found a bug report on prat addon similar to the same issue. maybe it can help? :)

[https://github.com/sylvanaar/prat-3-0/issues/114](url)

**Comment by Pazza** [comment]
Thank you, I will look into how this is affecting WIM. WIM only listens to incoming chat events. Not sure why it would be causing an issue.

**Comment by Pazza** [comment]
Can you confirm this is still an issue? WIM doesn't manage joining and leaving channels and really shouldn't be the cause of this problem. WIM only listens for chat message events and delivers them to the UI. Might have been another addon you are using. In this case Prat?

**Comment by Pazza** [comment]
With only WIM on, I enter and leave city and trade leaves and auto rejoins as it should.

**Comment by Faycop** [comment]
Thanks for the feedback! I still have the issue but now I can exclude WIM from the hypothesis :)

I don't use Prat, WIM is enough :D
