### ISSUE TITLE
WIM Breaks Weak Aura Links

### ISSUE THREAD

**Issue by Gogo1951** [Legacy-of-Sylvanaar/wow-instant-messenger#37]
I can't send a Weak Aura via WIM, I have to post it in raid.

BUT... sending it via PM without WIM installed works.

**Comment by Pazza** [comment]
I saw your screenshot from the other post. As a temp fix, disable emoticons in WIM. Probably same issue you're having with WA. I'll have to revisit this... AGAIN :-(

**Comment by Gogo1951** [comment]
Thanks mate, I know it's gotta be frustrating. WIM is great though!

**Comment by Pazza** [comment]
This should be fixed now.
