### ISSUE TITLE
WIM 3 update for WoW retail v10.0.7/10.1.0.

### ISSUE THREAD

**Issue by MelchiorGaspar** [Legacy-of-Sylvanaar/wow-instant-messenger#38]
Hi WoW Instant Messenger 3  (aka WIM-3) developers,

I was wondering if we could please get at least a .toc bump for WoW retail for v10.0.7 and 10.1.0 when it comes.
or if there are any bugs to be put to the axe.. I can report if I notice anything wrong.. as I like to do.

so far I only just re-subbed back for this month the other day and haven't done too much with retail in a long time but I can help test if need be.

**Desktop:**
 - OS: Windows 11 Pro
 - Version v22H2 22621.1555

 current versions:
WoW-retail v10.0.7.49267
Battle.net client (release channel): v2.19.0.14062

please and thx for one of my favorite and must have WoW addons. ^_^

ps: I have noticed no commits since March this year?
are you guys ok?

**Comment by Pazza** [comment]
TOCs will be updated. All is OK, just have not been playing and have been very busy with work.

**Comment by MelchiorGaspar** [comment]
hey Pazza,
ty for your reply.
I see you have just been busy with work.
I am glad to hear you are ok. ^_^ :D

**Comment by MelchiorGaspar** [comment]
ooh ok, I will grab that then.

**Comment by MelchiorGaspar** [comment]
hey Pazza,
 retail v10.1.0 is out now and could use a update check for toc etc.
if you can find the time that is. :D
