### ISSUE TITLE
Linking WoW items bugs out

### ISSUE THREAD

**Issue by TNBF1983** [Legacy-of-Sylvanaar/wow-instant-messenger#41]
**Describe the bug**
When you link a item it creates a mile long of text - almost like a long link of the item.

**To Reproduce**
1. Go to '...' Engage a whisper...
2. Click on '....' Whisper yourself a item link from wow... Send...

**Expected behavior**

Linking - [Obsidian Seared Crusher |A:Professions-ChatIcon-Quality-Tier5:17:17::1|a]

Turns into -
[05/08/2023]
`[05/08/2023]
<br><font color='#ffa900'>16:50</font><font color='#8f08c2'> [W From] <font color='#d8d8d8'>[</font><font color='#d8bc3f'>70</font>:<font color='#f48cba'>Roameo</font><font color='#d8d8d8'>]</font>: <font color='#a335ee'>[Obsidian Seared Crusher |A:Professions-ChatIcon-Quality-Tier5:17:17::1|a]</font></font>
`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 10.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BiXia1990** [comment]
Hey, same problem here... When an item was linkend in the WIM Window it looks like this -> [https://imgur.com/a/uZ5axvV](url)
Any fix for this issue?
Best regards!

**Comment by Pazza** [comment]
This should be fixed now.
