### ISSUE TITLE
Lua error on each whisper

### ISSUE THREAD

**Issue by Arcane321** [Legacy-of-Sylvanaar/wow-instant-messenger#45]
I cant seem to get the whole string

but as following 

delegate is blacklisted (unknown function)
s/WIM/Libs/LibChatHandler-1.0/LibChatHandler-1.0.lua:252 is blacklisted (unknown function)

![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/130360755/940eb81f-e69e-448b-bdf9-4fd8af81bc2f)

**Comment by Pazza** [comment]
What game version? 

@MysticalOS you ever see something like this?

**Comment by Arcane321** [comment]
![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/130360755/9ea62b93-8603-4859-94f5-7078482c02ce)

**Comment by Arcane321** [comment]
> What game version?
> 
> @MysticalOS you ever see something like this?

I figuered out what is was, it was another addon interfering with WIM (!NOFLASH)
