### ISSUE TITLE
Can't interact with "potentially inappropriate" message

### ISSUE THREAD

**Issue by shane3617** [Legacy-of-Sylvanaar/wow-instant-messenger#49]
unable to click on the 'Show Message' link

![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/76692725/be6855c1-b543-47a9-894c-50baf5654125)

**Comment by Jaidy88** [comment]
same

**Comment by Bruro** [comment]
same

**Comment by dartraiden** [comment]
I even turned off censoring messages, but I still can’t read them in win

**Comment by MaQubo** [comment]
same here, how can i fix it or i will download another chat addon.

**Comment by Alathaia83** [comment]
> I even turned off censoring messages, but I still can’t read them in WIM

Same...pls fix

**Comment by harveylx** [comment]
Can we get some acknowledgement of this issue? Can't even read any messages

**Comment by zaphon** [comment]
Yeah this is still happening. I've tried disabling censoring of messages but I still get this and no way to click [Show Message] from WIM.

**Comment by HolgerDKz** [comment]
This is still happening

![WIM fejl](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/23744656/8dfbfa13-9d4a-480c-98a7-525c3842351d)

**Comment by Pazza** [comment]
I just posted an update. I added a workaround for this. implementing the same behavior as the default UI is too complicated so WIM will ignore these messages and deliver them directly to the default chat frame instead.
