### ISSUE TITLE
Lua error when clicking a player name inside WIM chat box

### ISSUE THREAD

**Issue by rlesko** [Legacy-of-Sylvanaar/wow-instant-messenger#5]
> Message: Interface\FrameXML\ChatFrame.lua:4138: attempt to index local 'editBox' (a nil value)
> Time: Mon Feb 28 09:05:10 2022
> Count: 21
> Stack: Interface\FrameXML\ChatFrame.lua:4138: attempt to index local 'editBox' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\FrameXML\ChatFrame.lua"]:4138: in function <Interface\FrameXML\ChatFrame.lua:4126>
> [string "=[C]"]: in function `ChatEdit_ActivateChat'
> [string "@Interface\FrameXML\ChatFrame.lua"]:3716: in function <Interface\FrameXML\ChatFrame.lua:3705>
> [string "=[C]"]: in function `ChatFrame_OpenChat'
> [string "@Interface\FrameXML\ChatFrame.lua"]:3790: in function <Interface\FrameXML\ChatFrame.lua:3782>
> [string "@Interface\AddOns\WIM\Sources\Hooks.lua"]:117: in function `ChatFrame_SendTell'
> [string "@Interface\FrameXML\ItemRef.lua"]:68: in function <Interface\FrameXML\ItemRef.lua:1>
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua"]:3535: in function `SetItemRef'
> [string "@Interface\FrameXML\ChatFrame.lua"]:3682: in function <Interface\FrameXML\ChatFrame.lua:3681>
> [string "=[C]"]: in function `ChatFrame_OnHyperlinkShow'
> [string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:1906: in function `fun'
> [string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:393: in function <Interface\AddOns\WIM\Sources\WindowHandler.lua:385>
> [string "@Interface\AddOns\WIM\Sources\WindowHandler.lua"]:709: in function <Interface\AddOns\WIM\Sources\WindowHandler.lua:709>
> 
> Locals: 

This issue happens when I click the name of a player inside the WIM chat box. Is this a known issue? i'm not sure why this happens. It is 100% reproducible on Classic Season of Mastery.

**Comment by MelchiorGaspar** [comment]
me too. for wrath classic, v3.4.1
using WIM v3.10.7

**Comment by MelchiorGaspar** [comment]
thx for fixing it. :D ^_^
