### ISSUE TITLE
Unable to click Questie Links (Wow Classic HC)

### ISSUE THREAD

**Issue by Wintercypher** [Legacy-of-Sylvanaar/wow-instant-messenger#50]
**Describe the bug**
Unable to click Questie links within the WIM windows. Links work in all other chat areas. Confirmed other links and urls are functioning. 

**To Reproduce**
1. Send message to friend
2. Shift click in Quest from Quest Log
3. Hit enter to send message

**Expected behavior**
Text should be clickable but it appears as plain text. 

**Additional context**
WIM version 3.10.10 has a change log item regarding the questie links. I tried using the code line (below) within 
`theMsg, results = string.gsub(theMsg, "(|H[^|]+|h.-|h|r)", function(theLink)`
- Emoticons.lua
- URLHandler.lua

This did not resolve the issue. 

I love this addon and I share it daily with guildies. I just wish this could also work.

**Comment by anon1231823** [comment]
Same issue in SoD. Questie links don't work.
