### ISSUE TITLE
Support for CUSTOM_CLASS_COLORS

### ISSUE THREAD

**Issue by Road-block** [Legacy-of-Sylvanaar/wow-instant-messenger#54]
**Is your feature request related to a problem? Please describe.**
With the advent of Season of Discovery the request for custom class coloring (particularly to separate the paladin / shaman pink) has come to the forefront again.
Addons like ClassColors despite being end of life still have a functioning core and are used by a lot of players.

**Describe the solution you'd like**
I'd like WIM to use the CUSTOM_CLASS_COLORS global if available and fall back to RAID_CLASS_COLORS if not.

**Describe alternatives you've considered**
There's no other universal solutions for custom class coloring without causing taint issues (can't modify the blizzard table)

**Additional context**
A host of very popular addons already support CUSTOM_CLASS_COLORS either for historical reasons (support was added years back when custom class coloring was more popular) or recently added support for it. (ElvUI, WeakAuras, SexyMap, Postal, Pitbull, ThreatClassic, TipTac, Talented, MRT to name but a few)
Would be nice to see WIM follow suite :)

At the simplest, adding support consists of 2 edits.
- [/Sources/Constants.lua#L137](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/blob/9ba1490acdc301722da9167dbd3272814edae76d/Sources/Constants.lua#L137)
- [/Sources/Constants.lua#L147](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/blob/9ba1490acdc301722da9167dbd3272814edae76d/Sources/Constants.lua#L147) 
changed to
```lua
local classColorTable = (_G.CUSTOM_CLASS_COLORS or _G.RAID_CLASS_COLORS)[englishClass];
```
and that's it ;)

**Comment by Pazza** [comment]
I can add this in sure.

**Comment by Road-block** [comment]
I realized I have push permissions and it was a trivial change so I added it in https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/commit/3635f1baa8a88ef76037d43bc2e20234bd80a1be
I waited till you did a release as I didn't want to sneak it in. But it's already been included in the next alpha.

**Comment by Pazza** [comment]
All good. Nothing gets sneaked in, I have to approve the merges. Appreciate the contribution.
