### ISSUE TITLE
Wrap text 

### ISSUE THREAD

**Issue by anon1231823** [Legacy-of-Sylvanaar/wow-instant-messenger#56]
The string here goes out the window, maybe you can have it wrap around to fit within?

![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/67269448/4df41ca5-9778-4ebf-beb7-2ec49d28cd88)

**Comment by Pazza** [comment]
I notice this is  the same on English translations. To be honest, it will require a lot of retooling to remedy and I don't think its worth it at this time. Its easier to just update the text.
