### ISSUE TITLE
TabHandler bug - unable to change tabs until reload

### ISSUE THREAD

**Issue by trying-to-function** [Legacy-of-Sylvanaar/wow-instant-messenger#6]
**Describe the bug**
Tabs break until reload.

My settings file: [WIM.lua.txt](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/files/8157146/WIM.lua.txt) (remove the `.txt` file extension)

```
Date: 2022-02-28 15:49:31
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\WIM\Sources\TabHandler.lua line 486:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame2:SetPoint.
Debug:
   [string "@TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [string "=[C]"]: ?
   [string "=[C]"]: SetPoint()
   [string "@WIM\Sources\TabHandler.lua"]:486: JumpToTab()
   [string "@WIM\Sources\TabHandler.lua"]:332:
      WIM\Sources\TabHandler.lua:327
```

**To Reproduce**
1. Start two conversations with tabs enabled
2. Change tabs
3. Move the WIM window from the text box to somewhere else on the screen
4. Change tabs
5. Repeat until the error happens

**Expected behavior**
No errors happen, able to change tabs without issue

**Comment by Pazza** [comment]
Dplicate of #11
