### ISSUE TITLE
Update URL handler to work with SODWCL

### ISSUE THREAD

**Issue by Sleepywalker69** [Legacy-of-Sylvanaar/wow-instant-messenger#73]
Currently the URL handler doesn't work with SoD WCL. There was a closed topic which I have seen but it looks like WCL changed the URL again so it'll need updating.

Here's my proposed change:
-- Adding SoM Warcraft Logs link
    {
        title = "Warcraft Logs Season of Mastery",
        url = "https://sod.warcraftlogs.com/character/{us/eu}/{realm}/{user}"
    },

**Comment by Pazza** [comment]
Thank you for your contribution.

**Comment by Sleepywalker69** [comment]
> Thank you for your contribution.

I'm sorry I made a minor mistake with the code, Please change {us/eu} to {eu/us} as the addon seems to not like it the other way around.
