### ISSUE TITLE
Disable whispers and not other channels

### ISSUE THREAD

**Issue by BrianDawson** [Legacy-of-Sylvanaar/wow-instant-messenger#78]
**Is your feature request related to a problem? Please describe.**
I only want to use this for guild chat because I'm always missing messages as a GM, but I do not want whispers to also be enabled.

**Describe the solution you'd like**
Give an option to only disable whispers like how you can enable/disable other specific channels.

**Describe alternatives you've considered**
Finding another addon or making my own just for this. I want it for the notification. 

**Additional context**
 None.

**Comment by Pazza** [comment]
The core of the app is based on whispers. Everything else is an added feature. Your best option to accomplish what you're asking for is to create a filter under the whisper options, ignoring all messages:

![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/1767561/24db0a0a-fd41-4c2b-9105-746207efef93)

Then disable all the behaviors in Window Behaviors for whispers.
