### ISSUE TITLE
Implementation with "TwitchEmotesv2" within WIM interface

### ISSUE THREAD

**Issue by samjuan0** [Legacy-of-Sylvanaar/wow-instant-messenger#8]

**Comment by Pazza** [comment]
On curse I have a beta. Please try it and see if it fixes the broken emotes.

**Comment by samjuan0** [comment]
Do you guys have a discord? Bloody excellent application mate, one of my
favourite addons!

**Comment by Pazza** [comment]
🙂 there is a discord but it's not really used in the way you think. 

https://discord.gg/bh72A2Q6

I see what you mean about the twitch menu, i will have to see if this is trivial to add it not. 

As for the emotes displaying, are you using the beta or the stable release. Prior to the beta, it was reported that they did not show up correctly. I just haven't had anyone to test it.

**Comment by samjuan0** [comment]
Emote images icons are currently working in WIM
But no easy choose menu

**Comment by Pazza** [comment]
I reached out to the dev of the addon and directed him to the API within Wim what he might be able to use to add what you are looking for.

**Comment by Pazza** [comment]
I have fixed the twitchemote issue (not displaying correctly due to parsing issues with WIM's internal emoticons). I have also worked with the developer of TwitchEmotesV2 and he will be posting a release that will include the autocomplete support within WIM.

**Comment by samjuan0** [comment]
Hello John. Sorry I didn't clarify the issue, at the moment the emotes are
being shown within WIM. But I can't search for the emote I'm looking to use
within WIM.

Here is a photo to illustrate.

https://i.imgur.com/UWQtNRP.jpg

This GUI is what I want within WIM.

https://i.imgur.com/yApxD6L.png

But no GUI comes up.

https://i.imgur.com/lZODG2M.png
