### ISSUE TITLE
Auto Hide-Restore windows no longer works

### ISSUE THREAD

**Issue by jsauerland** [Legacy-of-Sylvanaar/wow-instant-messenger#81]
**Describe the bug**
I've unchecked 'auto hide/restore windows'. It still continues to supress and hide WIM during combat for unknown reason. 

**To Reproduce**

Enter combat. WIM does not appear, whisper appears in line

**Comment by Pazza** [comment]
Look at the Window Behaviors in options. (Whispers and Chat has its own rules).

There are window behaviors for various states of game place (while in combat or resting for example). Look at the tabs for the particular states and set your desired preferences.

![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/1767561/5195916b-f84d-4b03-9d92-a3ae31c712a3)

Alternatively, if you always want it to behave the same for all states, you can check the following option.

![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/1767561/cf75e018-dd44-4176-96e9-22ef6cbaf92e)
