### ISSUE TITLE
No sound when receiving whispers. Also history is not being recorded.

### ISSUE THREAD

**Issue by xGux** [Legacy-of-Sylvanaar/wow-instant-messenger#82]
Buggrabbers reads the following:

315x WIM/Modules/Sounds.lua:102: attempt to index field '?' (a nil value)
[string "@WIM/Modules/Sounds.lua"]:102: in function `fun'
[string "@WIM/WIM.lua"]:343: in function `CallModuleFunction'
[string "@WIM/Modules/WhisperEngine.lua"]:368: in function `handler'
[string "@WIM/Libs/LibChatHandler-1.0-25/LibChatHandler-1.0.lua"]:267: in function <...s/WIM/Libs/LibChatHandler-1.0/LibChatHandler-1.0.lua:252>
[string "@WIM/Libs/LibChatHandler-1.0-25/LibChatHandler-1.0.lua"]:311: in function <...s/WIM/Libs/LibChatHandler-1.0/LibChatHandler-1.0.lua:299>

Locals:
self = <table> {
 enabled = true
 dPrint = <function> defined @WIM/WIM.lua:290
 RegisterWidget = <function> defined @WIM/WIM.lua:292
 PostEvent_Whisper = <function> defined @WIM/Modules/Sounds.lua:99
 canDisable = false
 VARIABLES_LOADED = <function> defined @WIM/Modules/Sounds.lua:94
 RegisterEvent = <function> defined @WIM/WIM.lua:287
 PostEvent_WhisperInform = <function> defined @WIM/Modules/Sounds.lua:114
 db_defaults = <table> {
 }
 enableByDefault = true
 title = "Sounds"
 Enable = <function> defined @WIM/WIM.lua:288
 db = <table> {
 }
 resources = <table> {
 }
 hasWidget = false
 Disable = <function> defined @WIM/WIM.lua:289
}
msg = "gracias!"
user = "Madmárdigan"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
playSound = <function> defined @WIM/Modules/Sounds.lua:83

**Comment by Pazza** [comment]
Go into WIM and update your selection for what sound you'd like played when you receive a message. WIM expands access to sounds that other addon's share, if you remove an addon and the sound is no longer available or another addon, removes a sound it had packaged in the past, you can get this error.

**Comment by xGux** [comment]
The  sounds I selected are all available and can play when i test them from this window:
![image](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/132195867/392fa74b-02b8-4d0c-b25b-aa3d713efd23)
Nevertheless the error is still present.

I'll disable sound and see if it reproduces.

**Comment by Pazza** [comment]
Try changing the sound and then changing it back. `WIM/Modules/Sounds.lua:102: attempt to index field '?' (a nil value)` indicates that the sound its trying to load is not named or saved properly. Its not able to index it. 

If its still not working, its very possible that something else is breaking it.

**Comment by Pazza** [comment]
I think i found the problem. I will post a fix in a moment.

**Comment by xGux** [comment]
Fixed the issue with the new release. 
Thanks
