### ISSUE TITLE
War within beta error

### ISSUE THREAD

**Issue by Axejess** [Legacy-of-Sylvanaar/wow-instant-messenger#84]
**Describe the bug**

**To Reproduce**
1.start war within beta 
2. try to do a /w
3. See error

Message: Interface/AddOns/WIM/Sources/WindowHandler.lua:359: attempt to call upvalue 'GetMouseFocus' (a nil value)
Time: Fri Jun 14 13:12:02 2024
Count: 13
Stack: Interface/AddOns/WIM/Sources/WindowHandler.lua:359: attempt to call upvalue 'GetMouseFocus' (a nil value)
[string "@Interface/AddOns/WIM/Sources/WindowHandler.lua"]:359: in function <Interface/AddOns/WIM/Sources/WindowHandler.lua:357>

Locals: self = WIM_WindowHelperFrame {
 flash = WIM_WindowHelperFrameFlash {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetMouseFocus' (a nil value)"
GetMouseFocus = nil
WIM = <table> {
 addonTocName = "WIM"
 tblInUse = <table> {
 }
 modules = <table> {
 }
 windows = <table> {
 }
 debug = false
 Menu = WIM3Menu {
 }
 lastState = "resting"
 db = <table> {
 }
 lists = <table> {
 }
 useProtocol2 = true
 ctxMenu = <table> {
 }
 constants = <table> {
 }
 L = <table> {
 }
 O = <table> {
 }
 S = <table> {
 }
 ChatUserList = WIM3_ChatUserList {
 }
 isModernApi = true
 env = <table> {
 }
 tblAvailable = <table> {
 }
 curState = "resting"
 nextColor = <table> {
 }
 isInitialized = true
 history = <table> {
 }
 filters = <table> {
 }
 armoryLinks = <table> {
 }
 db_defaults = <table> {
 }
 WindowParent = WIM_UIParent {
 }
 options = <table> {
 }
 Notifications = <table> {
 }
 beta = false
 chatFilters = <table> {
 }
 libs = <table> {
 }
 stats = <table> {
 }
 windowsByAge = <table> {
 }
 version = "3.11.0-1-g69ba9dd"
}
resizeFrame = WIM_WindowResizeFrame {
 widgetName = "resize"
}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pazza** [comment]
please try the beta version posted on curse

**Comment by Axejess** [comment]
yeah it works (3.12.0-beta2) it still generates some errors but at least it start working thanks!

**Comment by Pazza** [comment]
@Axejess thanks for confirming. I'm waiting for a beta invite, till then, I'm kinda fixing it blindly.

**Comment by CherylAoife** [comment]
While the addon works in TWW Beta, I'm still getting the error as listed above with the latest version 3.12.0-beta2

**Comment by Pazza** [comment]
Fixed
