### ISSUE TITLE
can a multi-client .toc(s) be added?

### ISSUE THREAD

**Issue by MelchiorGaspar** [Legacy-of-Sylvanaar/wow-instant-messenger#9]
I have noticed that WoW Classic supports multi-client .toc format for a while now 
and would like to see it on WIM as well... :D :D

WIM.toc only stores value for WoW-retail :(

example..
tullaRange addon..

tullaRange.toc            = WoW retail
tullaRange_TBC.toc    = Wow classic, burning crusade
tullaRange_Vanilla.toc = WoW classic, vanilla

EDIT:
ooh, you release three versions for all supported WoW clients..
hmm..

**Comment by Pazza** [comment]
Yes the packager generates builds for each client. Can I close this issue?

**Comment by MelchiorGaspar** [comment]
ok, close it you want..  O_o :(

**Comment by Pazza** [comment]
Well I don't want to dismiss your request. Is there a purpose to maintain several TOC files if they are being packaged separately?

**Comment by MelchiorGaspar** [comment]
is there coding any different in each build/release/package?
I use WowUp to manage updates for WoW retail and bcc...
it some times seems to have issues showing the correct game version supported..
not sure.. but that can be fixed by using a multi-toc format... I guess.. hmm...

**Comment by MelchiorGaspar** [comment]
ok, np. thx for your time.
